### ISSUE TITLE
General process for creating a new lab should include levels of editing and testing expectations

### ISSUE THREAD

**Issue by annegentle** [CiscoDevNet/devnet-writing-guidelines#8]
@adrienne-at-work This issue can capture some ideas for testing and editing processes for Learning Labs. 

I think we talked about:
- testing by having someone in support walk through each lab and try the steps and code
- spell check test in the automation in LL
- link check test in the automation in LL
- images test in the automation in LL
- JSON test (already exists in the automation in LL), but I'd like to enhance it to be sure there are titles for every file reference

Can you think of others? Reply here so we capture.

**Comment by annegentle** [comment]
@bigevilbeard I'd love your input here too - can you think of automated tests we could run on the lab content?

**Comment by bigevilbeard** [comment]
Just a couple come to mimd

* readme is complete:
  * What does this learning lab do?
  * Why is this learning lab useful?
  * How do I get started?
  * Where can I get more help, if I need it?
  * How to file a bug report
  * How to suggest a new feature
* Test sandbox links

**Comment by annegentle** [comment]
Ah, yes! Love the README idea @bigevilbeard. I got a draft started here to put in the example: https://github.com/CiscoDevNet/devnet-writing-guidelines/pull/9 I should add more with your set of questions to be answered!
